#!/usr/bin/env python3
"""
CoreFlow Autonomous — Thermal Predictor v1.2 (18-feature contract)

PROVENANCE: without --data, the model is trained on SYNTHETIC trajectories
generated by this script. Its holdout metrics describe the generator, not a
real device, and the artifact is not device-validated. Use --data with real
per-device traces before relying on the model's predictions.

Trains a compact regressor that predicts thermal temperature (°C) a few
monitor ticks ahead, then exports a float32 ONNX model compatible with the
C++ ThermalPredictor in src/thermal_predictor.cpp.

Feature order is FROZEN and MUST match the C++ side:

  0  cpu_utilization
  1  load1
  2  mem_available_ratio
  3  thermal_current_c
  4  thermal_delta_c
  5  charging
  6  battery_temperature_c
  7  battery_current_a
  8  battery_voltage_v
  9  uptime_delta_s
 10  thermal_trend          (-1 falling, 0 unknown, 0.5 stable, 1 rising)
 11  memory_trend
 12  load_trend
 13  runtime_confidence
 14  hottest_thermal_c
 15  thermal_spread_c       (hottest - primary, >= 0)
 16  io_total_kb_s
 17  battery_level_percent

Input tensor name : float_input
Input shape       : [N, 18] float32
Output            : [N, 1]  float32  (predicted °C)

Usage:
  python3 tools/train_coreflow_thermal_predictor_v1_2_18f.py \\
      --output module/system/etc/coreflow/thermal_predictor.onnx

Optional real logs (CSV with the 18 columns + target_thermal_c):
  python3 tools/train_coreflow_thermal_predictor_v1_2_18f.py \\
      --data my_thermal_traces.csv \\
      --output module/system/etc/coreflow/thermal_predictor.onnx
"""

from __future__ import annotations

import argparse
import hashlib
import os
import sys
from pathlib import Path

import numpy as np

FEATURE_NAMES = [
    "cpu_utilization",
    "load1",
    "mem_available_ratio",
    "thermal_current_c",
    "thermal_delta_c",
    "charging",
    "battery_temperature_c",
    "battery_current_a",
    "battery_voltage_v",
    "uptime_delta_s",
    "thermal_trend",
    "memory_trend",
    "load_trend",
    "runtime_confidence",
    "hottest_thermal_c",
    "thermal_spread_c",
    "io_total_kb_s",
    "battery_level_percent",
]

FEATURE_COUNT = 18
INPUT_NAME = "float_input"
HORIZON_TICKS = 3
RNG_SEED = 42


def synthesize_dataset(n_samples: int = 24000, seed: int = RNG_SEED):
    """Physics-inspired synthetic trajectories for mobile SoC thermal dynamics."""
    rng = np.random.default_rng(seed)
    X = np.zeros((n_samples, FEATURE_COUNT), dtype=np.float64)
    y = np.zeros(n_samples, dtype=np.float64)

    # Start each episode from a realistic ambient band.
    temp = rng.uniform(34.0, 42.0, size=n_samples)
    hottest = temp + rng.uniform(0.0, 4.0, size=n_samples)
    cpu = rng.beta(2.0, 3.5, size=n_samples)  # skewed toward moderate load
    load1 = cpu * rng.uniform(1.5, 6.0, size=n_samples) + rng.normal(0, 0.3, size=n_samples)
    mem = np.clip(rng.normal(0.45, 0.15, size=n_samples), 0.05, 0.95)
    charging = rng.random(n_samples) < 0.35
    batt_temp = temp - rng.uniform(1.0, 6.0, size=n_samples)
    batt_curr = np.where(charging, rng.uniform(-1.8, -0.2, size=n_samples),
                         rng.uniform(0.05, 1.2, size=n_samples))
    batt_volt = rng.uniform(3.6, 4.35, size=n_samples)
    uptime_dt = rng.uniform(4.0, 6.0, size=n_samples)
    conf = np.clip(rng.normal(0.88, 0.08, size=n_samples), 0.5, 1.0)
    io = np.abs(rng.normal(800, 1200, size=n_samples))
    batt_pct = rng.uniform(5, 100, size=n_samples)

    # One-step deltas driven by cpu + charge heat + IO.
    delta = (
        0.35 * cpu
        + 0.08 * np.maximum(load1 - 2.0, 0.0)
        + np.where(charging, 0.12, -0.04)
        + 0.00002 * io
        + rng.normal(0.0, 0.15, size=n_samples)
    )
    # Trend encodings derived from delta.
    thermal_trend = np.where(delta > 0.25, 1.0, np.where(delta < -0.25, -1.0, 0.5))
    memory_trend = rng.choice([-1.0, 0.0, 0.5, 1.0], size=n_samples, p=[0.15, 0.2, 0.5, 0.15])
    load_trend = np.where(cpu > 0.65, 1.0, np.where(cpu < 0.25, -1.0, 0.5))

    spread = np.maximum(0.0, hottest - temp)

    X[:, 0] = cpu
    X[:, 1] = np.clip(load1, 0.0, 16.0)
    X[:, 2] = mem
    X[:, 3] = temp
    X[:, 4] = delta
    X[:, 5] = charging.astype(np.float64)
    X[:, 6] = batt_temp
    X[:, 7] = batt_curr
    X[:, 8] = batt_volt
    X[:, 9] = uptime_dt
    X[:, 10] = thermal_trend
    X[:, 11] = memory_trend
    X[:, 12] = load_trend
    X[:, 13] = conf
    X[:, 14] = hottest
    X[:, 15] = spread
    X[:, 16] = io
    X[:, 17] = batt_pct

    # Target: temperature HORIZON_TICKS steps ahead with mild non-linearity.
    y = (
        temp
        + HORIZON_TICKS * delta
        + 0.4 * spread * cpu
        + np.where(charging, 0.6, 0.0)
        + rng.normal(0.0, 0.25, size=n_samples)
    )
    y = np.clip(y, 28.0, 95.0)
    return X.astype(np.float32), y.astype(np.float32)


def load_csv(path: Path):
    import csv

    if not path.is_file():
        raise SystemExit(f"CSV file does not exist: {path}")

    rows = []
    required = FEATURE_NAMES + ["target_thermal_c"]
    with path.open(newline="", encoding="utf-8-sig") as f:
        reader = csv.DictReader(f)
        missing = [c for c in required if c not in (reader.fieldnames or [])]
        if missing:
            raise SystemExit(f"CSV missing columns: {missing}")
        for line_number, row in enumerate(reader, start=2):
            try:
                values = [float(row[c]) for c in required]
            except (TypeError, ValueError, KeyError) as exc:
                raise SystemExit(f"CSV line {line_number}: missing/non-numeric value ({exc})")
            if not np.isfinite(values).all():
                raise SystemExit(f"CSV line {line_number}: NaN/Inf values are not allowed")
            rows.append(values)

    if not rows:
        raise SystemExit("CSV contains no data rows")

    data = np.asarray(rows, dtype=np.float32)
    if not np.isfinite(data).all():
        raise SystemExit("CSV values overflow float32 or contain non-finite values")
    X, y = data[:, :FEATURE_COUNT], data[:, FEATURE_COUNT]

    # Reject obviously malformed labels rather than silently training on them.
    if np.any((y < -20.0) | (y > 150.0)):
        raise SystemExit("target_thermal_c contains values outside the supported sanity range [-20, 150] °C")
    if len(X) < 40:
        raise SystemExit(f"Need at least 40 valid rows; found {len(X)}")
    return X, y


def train_and_export(X, y, output: Path):
    from sklearn.neural_network import MLPRegressor
    from sklearn.pipeline import Pipeline
    from sklearn.preprocessing import StandardScaler
    from sklearn.metrics import mean_absolute_error, r2_score
    from skl2onnx import convert_sklearn
    from skl2onnx.common.data_types import FloatTensorType

    if X.ndim != 2 or X.shape[1] != FEATURE_COUNT:
        raise SystemExit(f"expected X shape [N,{FEATURE_COUNT}], got {X.shape}")
    if y.ndim != 1 or len(y) != len(X):
        raise SystemExit(f"expected y shape [N] matching X; got X={X.shape}, y={y.shape}")
    if len(X) < 40:
        raise SystemExit(f"Need at least 40 samples for a chronological holdout; found {len(X)}")
    if not np.isfinite(X).all() or not np.isfinite(y).all():
        raise SystemExit("Training data contains NaN or Inf")

    # Preserve chronology. Leave an embargo of HORIZON_TICKS rows between the
    # training and test segments because adjacent labels can share future ticks.
    test_count = max(8, int(round(len(X) * 0.15)))
    split = len(X) - test_count
    embargo = HORIZON_TICKS
    train_end = split - embargo
    if train_end < 30:
        raise SystemExit("Not enough rows after chronological split/embargo; collect more traces")
    X_train, y_train = X[:train_end], y[:train_end]
    X_test, y_test = X[split:], y[split:]
    print(f"split: chronological train={len(X_train)} embargo={embargo} test={len(X_test)}")

    # Compact MLP keeps the on-device model small and exports cleanly to ONNX.
    model = Pipeline(
        steps=[
            ("scale", StandardScaler()),
            (
                "mlp",
                MLPRegressor(
                    hidden_layer_sizes=(32, 16),
                    activation="relu",
                    solver="adam",
                    max_iter=400,
                    random_state=RNG_SEED,
                    early_stopping=True,
                    validation_fraction=0.1,
                    n_iter_no_change=20,
                ),
            ),
        ]
    )
    model.fit(X_train, y_train)

    pred = model.predict(X_test)
    mae = mean_absolute_error(y_test, pred)
    r2 = r2_score(y_test, pred) if len(y_test) >= 2 else float("nan")

    # Persistence baseline: predict that temperature remains at the current
    # thermal_current_c. A model should be compared to this simple baseline.
    baseline_pred = X_test[:, FEATURE_NAMES.index("thermal_current_c")]
    baseline_mae = mean_absolute_error(y_test, baseline_pred)
    improvement = baseline_mae - mae
    print(f"model holdout MAE={mae:.3f} °C  R2={r2:.4f}  n_test={len(y_test)}")
    print(f"persistence baseline MAE={baseline_mae:.3f} °C  improvement={improvement:+.3f} °C")
    if mae >= baseline_mae:
        print("WARNING: model does not outperform the persistence baseline on this holdout")

    initial_type = [(INPUT_NAME, FloatTensorType([None, FEATURE_COUNT]))]
    onnx_model = convert_sklearn(
        model,
        initial_types=initial_type,
        target_opset=13,
    )
    serialized = onnx_model.SerializeToString()

    # Validate the exported graph in memory. The output file is written only
    # after every available check passes, so a failed export never leaves a
    # bad model at the destination path.
    try:
        import onnx
        onnx.checker.check_model(onnx_model)
        onnx_checked = True
    except ImportError:
        onnx_checked = False
        print("NOTE: onnx not installed; ONNX graph checker skipped")

    try:
        import onnxruntime as ort
        session = ort.InferenceSession(serialized, providers=["CPUExecutionProvider"])
        probe = X_test[:min(8, len(X_test))].astype(np.float32)
        actual = session.run(None, {INPUT_NAME: probe})[0]
        expected = model.predict(probe).reshape(-1, 1)
        max_abs_error = float(np.max(np.abs(actual - expected)))
        print(f"ONNX Runtime parity max_abs_error={max_abs_error:.6f} °C")
        if not np.isfinite(actual).all() or max_abs_error > 0.05:
            raise SystemExit("ONNX Runtime parity check failed (non-finite output or error > 0.05 °C); no file written")
    except ImportError:
        print("NOTE: onnxruntime not installed; runtime parity check skipped")

    output.parent.mkdir(parents=True, exist_ok=True)
    tmp = output.with_name(output.name + ".tmp")
    tmp.write_bytes(serialized)
    os.replace(tmp, output)
    print(f"onnx_checker={'PASS' if onnx_checked else 'SKIPPED'}")
    print(f"wrote {output}  ({output.stat().st_size} bytes)")
    digest = hashlib.sha256(output.read_bytes()).hexdigest()
    print(f"wrote {output}  ({output.stat().st_size} bytes)")
    print(f"sha256={digest}")
    print(f"contract: input={INPUT_NAME} shape=[N,{FEATURE_COUNT}] float32")
    return digest


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("module/system/etc/coreflow/thermal_predictor.onnx"),
        help="Path for the exported ONNX model",
    )
    parser.add_argument(
        "--data",
        type=Path,
        default=None,
        help="Optional CSV with 18 feature columns + target_thermal_c",
    )
    parser.add_argument("--samples", type=int, default=24000, help="Synthetic sample count")
    args = parser.parse_args()

    if args.data is not None:
        print(f"loading real traces from {args.data}")
        X, y = load_csv(args.data)
    else:
        print(f"synthesizing {args.samples} samples (seed={RNG_SEED})")
        X, y = synthesize_dataset(args.samples)

    if X.shape[1] != FEATURE_COUNT:
        raise SystemExit(f"expected {FEATURE_COUNT} features, got {X.shape[1]}")
    if len(X) != len(y) or len(X) < 40:
        raise SystemExit(f"dataset needs matching X/y and at least 40 rows; X={X.shape}, y={y.shape}")
    if not np.isfinite(X).all() or not np.isfinite(y).all():
        raise SystemExit("dataset contains NaN/Inf")

    print(f"dataset X={X.shape} y={y.shape}")
    train_and_export(X, y, args.output)


if __name__ == "__main__":
    try:
        main()
    except ImportError as exc:
        print(
            "Missing dependency. Install with:\n"
            "  pip install numpy scikit-learn onnx skl2onnx\n"
            f"Details: {exc}",
            file=sys.stderr,
        )
        sys.exit(1)
