################################################################################
# cmake/install.cmake
#
# Installation and export configuration for packaging and redistribution
################################################################################

include(GNUInstallDirs)

function(coreflow_install_targets)
    # Install public headers
    install(
        DIRECTORY include/
        DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}
        FILES_MATCHING PATTERN "*.hpp" PATTERN "*.h"
    )
    
    # Install generated version header
    if(EXISTS "${CMAKE_CURRENT_BINARY_DIR}/include/coreflow_version.hpp")
        install(
            FILES "${CMAKE_CURRENT_BINARY_DIR}/include/coreflow_version.hpp"
            DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}
        )
    endif()
    
    # Install CMake config for consumers
    install(
        FILES
            "${CMAKE_CURRENT_SOURCE_DIR}/cmake/compiler_flags.cmake"
            "${CMAKE_CURRENT_SOURCE_DIR}/cmake/version.cmake"
        DESTINATION ${CMAKE_INSTALL_LIBDIR}/cmake/CoreFlow
    )
    
    # Install README and license
    if(EXISTS "${CMAKE_CURRENT_SOURCE_DIR}/README.md")
        install(
            FILES "${CMAKE_CURRENT_SOURCE_DIR}/README.md"
            DESTINATION ${CMAKE_INSTALL_DOCDIR}
        )
    endif()
    
    if(EXISTS "${CMAKE_CURRENT_SOURCE_DIR}/LICENSE")
        install(
            FILES "${CMAKE_CURRENT_SOURCE_DIR}/LICENSE"
            DESTINATION ${CMAKE_INSTALL_DOCDIR}
        )
    endif()
    
    message(STATUS "Installation targets configured")
    message(STATUS "  Include dir: ${CMAKE_INSTALL_INCLUDEDIR}")
    message(STATUS "  Library dir: ${CMAKE_INSTALL_LIBDIR}")
    message(STATUS "  CMake dir: ${CMAKE_INSTALL_LIBDIR}/cmake/CoreFlow")
    
endfunction()

################################################################################
# Generate CMake config package
################################################################################
function(coreflow_export_targets)
    # Generate and install CMakeConfig file for package discovery
    set(CONFIG_FILE "${CMAKE_CURRENT_BINARY_DIR}/CoreFlowConfig.cmake")
    
    file(WRITE "${CONFIG_FILE}"
        "# CoreFlow CMake configuration\n"
        "# Generated by CMake\n\n"
        "set(CoreFlow_FOUND TRUE)\n"
        "set(CoreFlow_VERSION ${PROJECT_VERSION})\n"
        "set(CoreFlow_INCLUDE_DIRS \${CMAKE_CURRENT_LIST_DIR}/../../include)\n"
    )
    
    install(
        FILES "${CONFIG_FILE}"
        DESTINATION ${CMAKE_INSTALL_LIBDIR}/cmake/CoreFlow
    )
    
endfunction()

################################################################################
# Create source distribution package
################################################################################
function(coreflow_create_source_package)
    set(PACKAGE_NAME "coreflow-${PROJECT_VERSION}")
    
    # Create tarball
    add_custom_target(dist
        COMMAND ${CMAKE_COMMAND} -E tar czf
            "${CMAKE_BINARY_DIR}/${PACKAGE_NAME}.tar.gz"
            --exclude=.git
            --exclude=build
            --exclude=".gitignore"
            -C "${CMAKE_CURRENT_SOURCE_DIR}/.." .
        WORKING_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}/.."
        COMMENT "Creating source distribution ${PACKAGE_NAME}.tar.gz"
    )
    
endfunction()
